### ISSUE TITLE
Multicall functionality fix 

### ISSUE THREAD

**Issue by 0xean** [elasticdao/sdk#106]
Multicall = true flag should intercept read calls and allows us to batch reads and limit the number of individual calls to alchemy. 

This is currently not working and we should diagnose and fix the issue.

**Comment by lrsaturnino** [comment]
@0xean I got it running.

![image](https://user-images.githubusercontent.com/4065310/138216826-c65397dd-fe25-490f-bc0a-fd917c3b9180.png)

Currently we have 3 recurring calls to get balances from WETH and EGT contracts.
